version: '3.7'

services:

  redis:
    image: redis
    expose:
      - 6379

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command:  bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 && celery -A celery_worker worker -l info"
    environment:
      - BROKER_URL=redis://redis:6379
      - RESULT_BACKEND=redis://redis:6379
    ports:
      - 8001:8000
    depends_on:
      - redis

  flower:
    image: mher/flower:0.9.5
    command: ['flower', '--broker=redis://redis:6379', '--basic_auth=abeo:Tunapork09','--port=5555']
    expose:
      - 5555
    ports:
      - 5557:5555
    depends_on:
      - redis
